import type { QuestionDifficulty, QuestionType } from './QuestionBank'

/**
 * Input for creating a new answer option.
 *
 * The option id and display order are generated by the service so the
 * caller only needs to provide the text and correctness flag.
 */
export interface CreateQuestionOption {
  /** Display text of the option. */
  text: string
  /** Whether this option is a correct answer. */
  isCorrect: boolean
}

/**
 * Command for creating a new question in the question bank.
 *
 * This contract is independent of the persistence model and maps the
 * backend Command/CommandHandler pattern to the frontend service layer.
 */
export interface CreateQuestionCommand {
  /** Identifier of the certification exam the question belongs to. */
  certificationExamId: string
  /** Optional identifier of the exam domain. When provided it must belong to the selected exam. */
  examDomainId?: string
  /** Optional identifier of the topic. When provided it must belong to the selected exam. */
  topicId?: string
  /** Optional external code, unique within the parent certification. */
  externalCode?: string
  /** Question statement. */
  statement: string
  /** Explanation of the correct answer. */
  explanation?: string
  /** Type of question. */
  type: QuestionType
  /** Difficulty level of the question. */
  difficulty: QuestionDifficulty
  /** Language of the question content. Defaults to "en". */
  language?: string
  /** Answer options for the question. At least two options are required. */
  options: CreateQuestionOption[]
  /** Optional tag ids associated with the question. */
  tagIds?: string[]
}
