import type { QuestionDifficulty, QuestionType } from './QuestionBank'

/**
 * Input for updating an answer option.
 *
 * The option id and display order are generated by the service so the
 * caller only needs to provide the text and correctness flag.
 */
export interface UpdateQuestionOption {
  /** Display text of the option. */
  text: string
  /** Whether this option is a correct answer. */
  isCorrect: boolean
}

/**
 * Command for updating an existing question in the question bank.
 *
 * The `id` field is optional. When provided it must match the identifier
 * supplied in the route path.
 */
export interface UpdateQuestionCommand {
  /** Optional route identifier. Must match the path identifier when provided. */
  id?: string
  /** Identifier of the certification exam the question belongs to. */
  certificationExamId: string
  /** Optional identifier of the exam domain. When provided it must belong to the selected exam. */
  examDomainId?: string
  /** Optional identifier of the topic. When provided it must belong to the selected exam. */
  topicId?: string
  /** Optional external code, unique within the parent certification. */
  externalCode?: string
  /** Question statement. */
  statement: string
  /** Explanation of the correct answer. */
  explanation?: string
  /** Type of question. */
  type: QuestionType
  /** Difficulty level of the question. */
  difficulty: QuestionDifficulty
  /** Language of the question content. Defaults to "en". */
  language?: string
  /** Answer options for the question. At least two options are required. */
  options: UpdateQuestionOption[]
  /** Optional tag ids associated with the question. */
  tagIds?: string[]
  /** Optional concurrency token. When provided it must match the current updatedAt value. */
  concurrencyToken?: string
}
